FROM openjdk:11-jdk
WORKDIR /app
COPY . .
RUN ls /app/src/main/resources/ # 이 줄 추가
ARG JAR_FILE=build/libs/backend-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} docker-springboot.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/docker-springboot.jar"]

